#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SmallERP_HuongTrinh")]
	public partial class IMS_TableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertInventoryStorage1(InventoryStorage1 instance);
    partial void UpdateInventoryStorage1(InventoryStorage1 instance);
    partial void DeleteInventoryStorage1(InventoryStorage1 instance);
    partial void InsertProductSale1(ProductSale1 instance);
    partial void UpdateProductSale1(ProductSale1 instance);
    partial void DeleteProductSale1(ProductSale1 instance);
    partial void InsertBOM(BOM instance);
    partial void UpdateBOM(BOM instance);
    partial void DeleteBOM(BOM instance);
    partial void InsertProductPurchase1(ProductPurchase1 instance);
    partial void UpdateProductPurchase1(ProductPurchase1 instance);
    partial void DeleteProductPurchase1(ProductPurchase1 instance);
    partial void InsertProductKind(ProductKind instance);
    partial void UpdateProductKind(ProductKind instance);
    partial void DeleteProductKind(ProductKind instance);
    #endregion
		
		public IMS_TableDataContext() : 
				base(global::IMS.Properties.Settings.Default.SmallERPConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public IMS_TableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IMS_TableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IMS_TableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IMS_TableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<InventoryStorage1> InventoryStorage1s
		{
			get
			{
				return this.GetTable<InventoryStorage1>();
			}
		}
		
		public System.Data.Linq.Table<ProductSale1> ProductSale1s
		{
			get
			{
				return this.GetTable<ProductSale1>();
			}
		}
		
		public System.Data.Linq.Table<BOM> BOMs
		{
			get
			{
				return this.GetTable<BOM>();
			}
		}
		
		public System.Data.Linq.Table<View_BOM_Extract> View_BOM_Extracts
		{
			get
			{
				return this.GetTable<View_BOM_Extract>();
			}
		}
		
		public System.Data.Linq.Table<View_BOM_No_Extract> View_BOM_No_Extracts
		{
			get
			{
				return this.GetTable<View_BOM_No_Extract>();
			}
		}
		
		public System.Data.Linq.Table<ProductPurchase1> ProductPurchase1s
		{
			get
			{
				return this.GetTable<ProductPurchase1>();
			}
		}
		
		public System.Data.Linq.Table<ProductKind> ProductKinds
		{
			get
			{
				return this.GetTable<ProductKind>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InventoryStorage")]
	public partial class InventoryStorage1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Address;
		
		private System.Nullable<bool> _IsGiven;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnIsGivenChanging(System.Nullable<bool> value);
    partial void OnIsGivenChanged();
    #endregion
		
		public InventoryStorage1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(250)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsGiven", DbType="Bit")]
		public System.Nullable<bool> IsGiven
		{
			get
			{
				return this._IsGiven;
			}
			set
			{
				if ((this._IsGiven != value))
				{
					this.OnIsGivenChanging(value);
					this.SendPropertyChanging();
					this._IsGiven = value;
					this.SendPropertyChanged("IsGiven");
					this.OnIsGivenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductSale")]
	public partial class ProductSale1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _InvoiceNo;
		
		private System.Nullable<int> _DiffNo;
		
		private System.Nullable<long> _CreatedDate;
		
		private string _CreatedDateEx;
		
		private System.Nullable<long> _InvoiceDate;
		
		private string _InvoiceDateEx;
		
		private System.Nullable<long> _IdStaff;
		
		private System.Nullable<long> _IdStaffSale;
		
		private System.Nullable<long> _IdCustomer;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<int> _Tax;
		
		private System.Nullable<decimal> _Discount;
		
		private System.Nullable<decimal> _Payment;
		
		private System.Nullable<bool> _IsDone;
		
		private System.Nullable<long> _IdBranch;
		
		private System.Nullable<bool> _IsGiven;
		
		private string _Kind;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnInvoiceNoChanging(string value);
    partial void OnInvoiceNoChanged();
    partial void OnDiffNoChanging(System.Nullable<int> value);
    partial void OnDiffNoChanged();
    partial void OnCreatedDateChanging(System.Nullable<long> value);
    partial void OnCreatedDateChanged();
    partial void OnCreatedDateExChanging(string value);
    partial void OnCreatedDateExChanged();
    partial void OnInvoiceDateChanging(System.Nullable<long> value);
    partial void OnInvoiceDateChanged();
    partial void OnInvoiceDateExChanging(string value);
    partial void OnInvoiceDateExChanged();
    partial void OnIdStaffChanging(System.Nullable<long> value);
    partial void OnIdStaffChanged();
    partial void OnIdStaffSaleChanging(System.Nullable<long> value);
    partial void OnIdStaffSaleChanged();
    partial void OnIdCustomerChanging(System.Nullable<long> value);
    partial void OnIdCustomerChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnTaxChanging(System.Nullable<int> value);
    partial void OnTaxChanged();
    partial void OnDiscountChanging(System.Nullable<decimal> value);
    partial void OnDiscountChanged();
    partial void OnPaymentChanging(System.Nullable<decimal> value);
    partial void OnPaymentChanged();
    partial void OnIsDoneChanging(System.Nullable<bool> value);
    partial void OnIsDoneChanged();
    partial void OnIdBranchChanging(System.Nullable<long> value);
    partial void OnIdBranchChanged();
    partial void OnIsGivenChanging(System.Nullable<bool> value);
    partial void OnIsGivenChanged();
    partial void OnKindChanging(string value);
    partial void OnKindChanged();
    #endregion
		
		public ProductSale1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo", DbType="NVarChar(50)")]
		public string InvoiceNo
		{
			get
			{
				return this._InvoiceNo;
			}
			set
			{
				if ((this._InvoiceNo != value))
				{
					this.OnInvoiceNoChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNo = value;
					this.SendPropertyChanged("InvoiceNo");
					this.OnInvoiceNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiffNo", DbType="Int")]
		public System.Nullable<int> DiffNo
		{
			get
			{
				return this._DiffNo;
			}
			set
			{
				if ((this._DiffNo != value))
				{
					this.OnDiffNoChanging(value);
					this.SendPropertyChanging();
					this._DiffNo = value;
					this.SendPropertyChanged("DiffNo");
					this.OnDiffNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="BigInt")]
		public System.Nullable<long> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDateEx", DbType="NVarChar(50)")]
		public string CreatedDateEx
		{
			get
			{
				return this._CreatedDateEx;
			}
			set
			{
				if ((this._CreatedDateEx != value))
				{
					this.OnCreatedDateExChanging(value);
					this.SendPropertyChanging();
					this._CreatedDateEx = value;
					this.SendPropertyChanged("CreatedDateEx");
					this.OnCreatedDateExChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="BigInt")]
		public System.Nullable<long> InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this.OnInvoiceDateChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDate = value;
					this.SendPropertyChanged("InvoiceDate");
					this.OnInvoiceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDateEx", DbType="NVarChar(50)")]
		public string InvoiceDateEx
		{
			get
			{
				return this._InvoiceDateEx;
			}
			set
			{
				if ((this._InvoiceDateEx != value))
				{
					this.OnInvoiceDateExChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDateEx = value;
					this.SendPropertyChanged("InvoiceDateEx");
					this.OnInvoiceDateExChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStaff", DbType="BigInt")]
		public System.Nullable<long> IdStaff
		{
			get
			{
				return this._IdStaff;
			}
			set
			{
				if ((this._IdStaff != value))
				{
					this.OnIdStaffChanging(value);
					this.SendPropertyChanging();
					this._IdStaff = value;
					this.SendPropertyChanged("IdStaff");
					this.OnIdStaffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStaffSale", DbType="BigInt")]
		public System.Nullable<long> IdStaffSale
		{
			get
			{
				return this._IdStaffSale;
			}
			set
			{
				if ((this._IdStaffSale != value))
				{
					this.OnIdStaffSaleChanging(value);
					this.SendPropertyChanging();
					this._IdStaffSale = value;
					this.SendPropertyChanged("IdStaffSale");
					this.OnIdStaffSaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCustomer", DbType="BigInt")]
		public System.Nullable<long> IdCustomer
		{
			get
			{
				return this._IdCustomer;
			}
			set
			{
				if ((this._IdCustomer != value))
				{
					this.OnIdCustomerChanging(value);
					this.SendPropertyChanging();
					this._IdCustomer = value;
					this.SendPropertyChanged("IdCustomer");
					this.OnIdCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tax", DbType="Int")]
		public System.Nullable<int> Tax
		{
			get
			{
				return this._Tax;
			}
			set
			{
				if ((this._Tax != value))
				{
					this.OnTaxChanging(value);
					this.SendPropertyChanging();
					this._Tax = value;
					this.SendPropertyChanged("Tax");
					this.OnTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="Money")]
		public System.Nullable<decimal> Discount
		{
			get
			{
				return this._Discount;
			}
			set
			{
				if ((this._Discount != value))
				{
					this.OnDiscountChanging(value);
					this.SendPropertyChanging();
					this._Discount = value;
					this.SendPropertyChanged("Discount");
					this.OnDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment", DbType="Money")]
		public System.Nullable<decimal> Payment
		{
			get
			{
				return this._Payment;
			}
			set
			{
				if ((this._Payment != value))
				{
					this.OnPaymentChanging(value);
					this.SendPropertyChanging();
					this._Payment = value;
					this.SendPropertyChanged("Payment");
					this.OnPaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDone", DbType="Bit")]
		public System.Nullable<bool> IsDone
		{
			get
			{
				return this._IsDone;
			}
			set
			{
				if ((this._IsDone != value))
				{
					this.OnIsDoneChanging(value);
					this.SendPropertyChanging();
					this._IsDone = value;
					this.SendPropertyChanged("IsDone");
					this.OnIsDoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBranch", DbType="BigInt")]
		public System.Nullable<long> IdBranch
		{
			get
			{
				return this._IdBranch;
			}
			set
			{
				if ((this._IdBranch != value))
				{
					this.OnIdBranchChanging(value);
					this.SendPropertyChanging();
					this._IdBranch = value;
					this.SendPropertyChanged("IdBranch");
					this.OnIdBranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsGiven", DbType="Bit")]
		public System.Nullable<bool> IsGiven
		{
			get
			{
				return this._IsGiven;
			}
			set
			{
				if ((this._IsGiven != value))
				{
					this.OnIsGivenChanging(value);
					this.SendPropertyChanging();
					this._IsGiven = value;
					this.SendPropertyChanged("IsGiven");
					this.OnIsGivenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kind", DbType="NVarChar(258)")]
		public string Kind
		{
			get
			{
				return this._Kind;
			}
			set
			{
				if ((this._Kind != value))
				{
					this.OnKindChanging(value);
					this.SendPropertyChanging();
					this._Kind = value;
					this.SendPropertyChanged("Kind");
					this.OnKindChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BOM")]
	public partial class BOM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _IdEx;
		
		private long _IdProductMain;
		
		private long _IdProductSub;
		
		private long _Quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnIdExChanging(System.Nullable<long> value);
    partial void OnIdExChanged();
    partial void OnIdProductMainChanging(long value);
    partial void OnIdProductMainChanged();
    partial void OnIdProductSubChanging(long value);
    partial void OnIdProductSubChanged();
    partial void OnQuantityChanging(long value);
    partial void OnQuantityChanged();
    #endregion
		
		public BOM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEx", DbType="BigInt")]
		public System.Nullable<long> IdEx
		{
			get
			{
				return this._IdEx;
			}
			set
			{
				if ((this._IdEx != value))
				{
					this.OnIdExChanging(value);
					this.SendPropertyChanging();
					this._IdEx = value;
					this.SendPropertyChanged("IdEx");
					this.OnIdExChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductMain", DbType="BigInt NOT NULL")]
		public long IdProductMain
		{
			get
			{
				return this._IdProductMain;
			}
			set
			{
				if ((this._IdProductMain != value))
				{
					this.OnIdProductMainChanging(value);
					this.SendPropertyChanging();
					this._IdProductMain = value;
					this.SendPropertyChanged("IdProductMain");
					this.OnIdProductMainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductSub", DbType="BigInt NOT NULL")]
		public long IdProductSub
		{
			get
			{
				return this._IdProductSub;
			}
			set
			{
				if ((this._IdProductSub != value))
				{
					this.OnIdProductSubChanging(value);
					this.SendPropertyChanging();
					this._IdProductSub = value;
					this.SendPropertyChanged("IdProductSub");
					this.OnIdProductSubChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="BigInt NOT NULL")]
		public long Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_BOM_Extract")]
	public partial class View_BOM_Extract
	{
		
		private long _Id;
		
		private System.Nullable<long> _IdEx;
		
		private long _IdProductMain;
		
		private long _IdProductSub;
		
		private long _Quantity;
		
		private string _Code;
		
		private string _Name;
		
		private string _UnitName;
		
		private System.Nullable<bool> _IsBOM;
		
		public View_BOM_Extract()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEx", DbType="BigInt")]
		public System.Nullable<long> IdEx
		{
			get
			{
				return this._IdEx;
			}
			set
			{
				if ((this._IdEx != value))
				{
					this._IdEx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductMain", DbType="BigInt NOT NULL")]
		public long IdProductMain
		{
			get
			{
				return this._IdProductMain;
			}
			set
			{
				if ((this._IdProductMain != value))
				{
					this._IdProductMain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductSub", DbType="BigInt NOT NULL")]
		public long IdProductSub
		{
			get
			{
				return this._IdProductSub;
			}
			set
			{
				if ((this._IdProductSub != value))
				{
					this._IdProductSub = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="BigInt NOT NULL")]
		public long Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UnitName
		{
			get
			{
				return this._UnitName;
			}
			set
			{
				if ((this._UnitName != value))
				{
					this._UnitName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBOM", DbType="Bit")]
		public System.Nullable<bool> IsBOM
		{
			get
			{
				return this._IsBOM;
			}
			set
			{
				if ((this._IsBOM != value))
				{
					this._IsBOM = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_BOM_No_Extract")]
	public partial class View_BOM_No_Extract
	{
		
		private long _Id;
		
		private System.Nullable<long> _IdEx;
		
		private long _IdProductMain;
		
		private long _IdProductSub;
		
		private long _Quantity;
		
		private string _Code;
		
		private string _Name;
		
		private string _UnitName;
		
		private System.Nullable<bool> _IsBOM;
		
		public View_BOM_No_Extract()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEx", DbType="BigInt")]
		public System.Nullable<long> IdEx
		{
			get
			{
				return this._IdEx;
			}
			set
			{
				if ((this._IdEx != value))
				{
					this._IdEx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductMain", DbType="BigInt NOT NULL")]
		public long IdProductMain
		{
			get
			{
				return this._IdProductMain;
			}
			set
			{
				if ((this._IdProductMain != value))
				{
					this._IdProductMain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductSub", DbType="BigInt NOT NULL")]
		public long IdProductSub
		{
			get
			{
				return this._IdProductSub;
			}
			set
			{
				if ((this._IdProductSub != value))
				{
					this._IdProductSub = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="BigInt NOT NULL")]
		public long Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UnitName
		{
			get
			{
				return this._UnitName;
			}
			set
			{
				if ((this._UnitName != value))
				{
					this._UnitName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBOM", DbType="Bit")]
		public System.Nullable<bool> IsBOM
		{
			get
			{
				return this._IsBOM;
			}
			set
			{
				if ((this._IsBOM != value))
				{
					this._IsBOM = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductPurchase")]
	public partial class ProductPurchase1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _InvoiceNo;
		
		private System.Nullable<int> _DiffNo;
		
		private System.Nullable<long> _CreatedDate;
		
		private string _CreatedDateEx;
		
		private System.Nullable<long> _InvoiceDate;
		
		private string _InvoiceDateEx;
		
		private System.Nullable<long> _IdStaff;
		
		private System.Nullable<long> _IdVendor;
		
		private System.Nullable<long> _Amount;
		
		private System.Nullable<long> _Discount;
		
		private System.Nullable<long> _Payment;
		
		private System.Nullable<bool> _IsDone;
		
		private System.Nullable<long> _IdBranch;
		
		private string _Kind;
		
		private System.Nullable<long> _IdCustomer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnInvoiceNoChanging(string value);
    partial void OnInvoiceNoChanged();
    partial void OnDiffNoChanging(System.Nullable<int> value);
    partial void OnDiffNoChanged();
    partial void OnCreatedDateChanging(System.Nullable<long> value);
    partial void OnCreatedDateChanged();
    partial void OnCreatedDateExChanging(string value);
    partial void OnCreatedDateExChanged();
    partial void OnInvoiceDateChanging(System.Nullable<long> value);
    partial void OnInvoiceDateChanged();
    partial void OnInvoiceDateExChanging(string value);
    partial void OnInvoiceDateExChanged();
    partial void OnIdStaffChanging(System.Nullable<long> value);
    partial void OnIdStaffChanged();
    partial void OnIdVendorChanging(System.Nullable<long> value);
    partial void OnIdVendorChanged();
    partial void OnAmountChanging(System.Nullable<long> value);
    partial void OnAmountChanged();
    partial void OnDiscountChanging(System.Nullable<long> value);
    partial void OnDiscountChanged();
    partial void OnPaymentChanging(System.Nullable<long> value);
    partial void OnPaymentChanged();
    partial void OnIsDoneChanging(System.Nullable<bool> value);
    partial void OnIsDoneChanged();
    partial void OnIdBranchChanging(System.Nullable<long> value);
    partial void OnIdBranchChanged();
    partial void OnKindChanging(string value);
    partial void OnKindChanged();
    partial void OnIdCustomerChanging(System.Nullable<long> value);
    partial void OnIdCustomerChanged();
    #endregion
		
		public ProductPurchase1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo", DbType="NVarChar(50)")]
		public string InvoiceNo
		{
			get
			{
				return this._InvoiceNo;
			}
			set
			{
				if ((this._InvoiceNo != value))
				{
					this.OnInvoiceNoChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNo = value;
					this.SendPropertyChanged("InvoiceNo");
					this.OnInvoiceNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiffNo", DbType="Int")]
		public System.Nullable<int> DiffNo
		{
			get
			{
				return this._DiffNo;
			}
			set
			{
				if ((this._DiffNo != value))
				{
					this.OnDiffNoChanging(value);
					this.SendPropertyChanging();
					this._DiffNo = value;
					this.SendPropertyChanged("DiffNo");
					this.OnDiffNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="BigInt")]
		public System.Nullable<long> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDateEx", DbType="NVarChar(50)")]
		public string CreatedDateEx
		{
			get
			{
				return this._CreatedDateEx;
			}
			set
			{
				if ((this._CreatedDateEx != value))
				{
					this.OnCreatedDateExChanging(value);
					this.SendPropertyChanging();
					this._CreatedDateEx = value;
					this.SendPropertyChanged("CreatedDateEx");
					this.OnCreatedDateExChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="BigInt")]
		public System.Nullable<long> InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this.OnInvoiceDateChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDate = value;
					this.SendPropertyChanged("InvoiceDate");
					this.OnInvoiceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDateEx", DbType="NVarChar(50)")]
		public string InvoiceDateEx
		{
			get
			{
				return this._InvoiceDateEx;
			}
			set
			{
				if ((this._InvoiceDateEx != value))
				{
					this.OnInvoiceDateExChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDateEx = value;
					this.SendPropertyChanged("InvoiceDateEx");
					this.OnInvoiceDateExChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStaff", DbType="BigInt")]
		public System.Nullable<long> IdStaff
		{
			get
			{
				return this._IdStaff;
			}
			set
			{
				if ((this._IdStaff != value))
				{
					this.OnIdStaffChanging(value);
					this.SendPropertyChanging();
					this._IdStaff = value;
					this.SendPropertyChanged("IdStaff");
					this.OnIdStaffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVendor", DbType="BigInt")]
		public System.Nullable<long> IdVendor
		{
			get
			{
				return this._IdVendor;
			}
			set
			{
				if ((this._IdVendor != value))
				{
					this.OnIdVendorChanging(value);
					this.SendPropertyChanging();
					this._IdVendor = value;
					this.SendPropertyChanged("IdVendor");
					this.OnIdVendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="BigInt")]
		public System.Nullable<long> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="BigInt")]
		public System.Nullable<long> Discount
		{
			get
			{
				return this._Discount;
			}
			set
			{
				if ((this._Discount != value))
				{
					this.OnDiscountChanging(value);
					this.SendPropertyChanging();
					this._Discount = value;
					this.SendPropertyChanged("Discount");
					this.OnDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment", DbType="BigInt")]
		public System.Nullable<long> Payment
		{
			get
			{
				return this._Payment;
			}
			set
			{
				if ((this._Payment != value))
				{
					this.OnPaymentChanging(value);
					this.SendPropertyChanging();
					this._Payment = value;
					this.SendPropertyChanged("Payment");
					this.OnPaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDone", DbType="Bit")]
		public System.Nullable<bool> IsDone
		{
			get
			{
				return this._IsDone;
			}
			set
			{
				if ((this._IsDone != value))
				{
					this.OnIsDoneChanging(value);
					this.SendPropertyChanging();
					this._IsDone = value;
					this.SendPropertyChanged("IsDone");
					this.OnIsDoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBranch", DbType="BigInt")]
		public System.Nullable<long> IdBranch
		{
			get
			{
				return this._IdBranch;
			}
			set
			{
				if ((this._IdBranch != value))
				{
					this.OnIdBranchChanging(value);
					this.SendPropertyChanging();
					this._IdBranch = value;
					this.SendPropertyChanged("IdBranch");
					this.OnIdBranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kind", DbType="NVarChar(50)")]
		public string Kind
		{
			get
			{
				return this._Kind;
			}
			set
			{
				if ((this._Kind != value))
				{
					this.OnKindChanging(value);
					this.SendPropertyChanging();
					this._Kind = value;
					this.SendPropertyChanged("Kind");
					this.OnKindChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCustomer", DbType="BigInt")]
		public System.Nullable<long> IdCustomer
		{
			get
			{
				return this._IdCustomer;
			}
			set
			{
				if ((this._IdCustomer != value))
				{
					this.OnIdCustomerChanging(value);
					this.SendPropertyChanging();
					this._IdCustomer = value;
					this.SendPropertyChanged("IdCustomer");
					this.OnIdCustomerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductKind")]
	public partial class ProductKind : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Code;
		
		private System.Nullable<bool> _IsColorDiff;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnIsColorDiffChanging(System.Nullable<bool> value);
    partial void OnIsColorDiffChanged();
    #endregion
		
		public ProductKind()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(5)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsColorDiff", DbType="Bit")]
		public System.Nullable<bool> IsColorDiff
		{
			get
			{
				return this._IsColorDiff;
			}
			set
			{
				if ((this._IsColorDiff != value))
				{
					this.OnIsColorDiffChanging(value);
					this.SendPropertyChanging();
					this._IsColorDiff = value;
					this.SendPropertyChanged("IsColorDiff");
					this.OnIsColorDiffChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

        public int RowNumber { get; set; }
    }
}
#pragma warning restore 1591
