#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SmallERP_SDIVINA")]
	public partial class IMS_ViewDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertInventoryInputItem1(InventoryInputItem1 instance);
    partial void UpdateInventoryInputItem1(InventoryInputItem1 instance);
    partial void DeleteInventoryInputItem1(InventoryInputItem1 instance);
    partial void InsertProduct1(Product1 instance);
    partial void UpdateProduct1(Product1 instance);
    partial void DeleteProduct1(Product1 instance);
    #endregion
		
		public IMS_ViewDataContext() : 
				base(global::IMS.Properties.Settings.Default.SmallERPConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public IMS_ViewDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IMS_ViewDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IMS_ViewDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IMS_ViewDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<InventoryInputItem1> InventoryInputItem1s
		{
			get
			{
				return this.GetTable<InventoryInputItem1>();
			}
		}
		
		public System.Data.Linq.Table<InventoryInputItemView1> InventoryInputItemView1s
		{
			get
			{
				return this.GetTable<InventoryInputItemView1>();
			}
		}
		
		public System.Data.Linq.Table<InventoryView1> InventoryView1s
		{
			get
			{
				return this.GetTable<InventoryView1>();
			}
		}
		
		public System.Data.Linq.Table<InventoryInputItemGroupView> InventoryInputItemGroupViews
		{
			get
			{
				return this.GetTable<InventoryInputItemGroupView>();
			}
		}
		
		public System.Data.Linq.Table<ProductCustomerCreditLimitView> ProductCustomerCreditLimitViews
		{
			get
			{
				return this.GetTable<ProductCustomerCreditLimitView>();
			}
		}
		
		public System.Data.Linq.Table<ProductView1> ProductView1s
		{
			get
			{
				return this.GetTable<ProductView1>();
			}
		}
		
		public System.Data.Linq.Table<Product1> Product1s
		{
			get
			{
				return this.GetTable<Product1>();
			}
		}
		
		public System.Data.Linq.Table<ProductPurchaseView1> ProductPurchaseView1s
		{
			get
			{
				return this.GetTable<ProductPurchaseView1>();
			}
		}
		
		public System.Data.Linq.Table<CustomerCreditLimitView> CustomerCreditLimitViews
		{
			get
			{
				return this.GetTable<CustomerCreditLimitView>();
			}
		}
		
		public System.Data.Linq.Table<ProductSaleView1> ProductSaleView1s
		{
			get
			{
				return this.GetTable<ProductSaleView1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InventoryInputItem")]
	public partial class InventoryInputItem1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Code;
		
		private System.Nullable<long> _DiffNo;
		
		private string _CodeEx;
		
		private System.Data.Linq.Binary _Barcode;
		
		private System.Nullable<bool> _Expiry;
		
		private string _ExpiryEx;
		
		private string _LottNo;
		
		private System.Nullable<long> _PriceIn;
		
		private System.Nullable<float> _Quantity;
		
		private System.Nullable<long> _IdProductPurchase;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDiffNoChanging(System.Nullable<long> value);
    partial void OnDiffNoChanged();
    partial void OnCodeExChanging(string value);
    partial void OnCodeExChanged();
    partial void OnBarcodeChanging(System.Data.Linq.Binary value);
    partial void OnBarcodeChanged();
    partial void OnExpiryChanging(System.Nullable<bool> value);
    partial void OnExpiryChanged();
    partial void OnExpiryExChanging(string value);
    partial void OnExpiryExChanged();
    partial void OnLottNoChanging(string value);
    partial void OnLottNoChanged();
    partial void OnPriceInChanging(System.Nullable<long> value);
    partial void OnPriceInChanged();
    partial void OnQuantityChanging(System.Nullable<float> value);
    partial void OnQuantityChanged();
    partial void OnIdProductPurchaseChanging(System.Nullable<long> value);
    partial void OnIdProductPurchaseChanged();
    #endregion
		
		public InventoryInputItem1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiffNo", DbType="BigInt")]
		public System.Nullable<long> DiffNo
		{
			get
			{
				return this._DiffNo;
			}
			set
			{
				if ((this._DiffNo != value))
				{
					this.OnDiffNoChanging(value);
					this.SendPropertyChanging();
					this._DiffNo = value;
					this.SendPropertyChanged("DiffNo");
					this.OnDiffNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeEx", DbType="NVarChar(50)")]
		public string CodeEx
		{
			get
			{
				return this._CodeEx;
			}
			set
			{
				if ((this._CodeEx != value))
				{
					this.OnCodeExChanging(value);
					this.SendPropertyChanging();
					this._CodeEx = value;
					this.SendPropertyChanged("CodeEx");
					this.OnCodeExChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="Binary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this.OnBarcodeChanging(value);
					this.SendPropertyChanging();
					this._Barcode = value;
					this.SendPropertyChanged("Barcode");
					this.OnBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expiry", DbType="Bit")]
		public System.Nullable<bool> Expiry
		{
			get
			{
				return this._Expiry;
			}
			set
			{
				if ((this._Expiry != value))
				{
					this.OnExpiryChanging(value);
					this.SendPropertyChanging();
					this._Expiry = value;
					this.SendPropertyChanged("Expiry");
					this.OnExpiryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryEx", DbType="NVarChar(250)")]
		public string ExpiryEx
		{
			get
			{
				return this._ExpiryEx;
			}
			set
			{
				if ((this._ExpiryEx != value))
				{
					this.OnExpiryExChanging(value);
					this.SendPropertyChanging();
					this._ExpiryEx = value;
					this.SendPropertyChanged("ExpiryEx");
					this.OnExpiryExChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LottNo", DbType="NVarChar(50)")]
		public string LottNo
		{
			get
			{
				return this._LottNo;
			}
			set
			{
				if ((this._LottNo != value))
				{
					this.OnLottNoChanging(value);
					this.SendPropertyChanging();
					this._LottNo = value;
					this.SendPropertyChanged("LottNo");
					this.OnLottNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceIn", DbType="BigInt")]
		public System.Nullable<long> PriceIn
		{
			get
			{
				return this._PriceIn;
			}
			set
			{
				if ((this._PriceIn != value))
				{
					this.OnPriceInChanging(value);
					this.SendPropertyChanging();
					this._PriceIn = value;
					this.SendPropertyChanged("PriceIn");
					this.OnPriceInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Real")]
		public System.Nullable<float> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductPurchase", DbType="BigInt")]
		public System.Nullable<long> IdProductPurchase
		{
			get
			{
				return this._IdProductPurchase;
			}
			set
			{
				if ((this._IdProductPurchase != value))
				{
					this.OnIdProductPurchaseChanging(value);
					this.SendPropertyChanging();
					this._IdProductPurchase = value;
					this.SendPropertyChanged("IdProductPurchase");
					this.OnIdProductPurchaseChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InventoryInputItemView")]
	public partial class InventoryInputItemView1
	{
		
		private long _Id;
		
		private string _Code;
		
		private string _Name;
		
		private System.Nullable<long> _DiffNo;
		
		private string _CodeEx;
		
		private System.Data.Linq.Binary _Barcode;
		
		private System.Nullable<bool> _Expiry;
		
		private string _ExpiryEx;
		
		private string _LottNo;
		
		private System.Nullable<float> _Quantity;
		
		private System.Nullable<long> _PriceIn;
		
		private System.Nullable<long> _IdProductPurchase;
		
		public InventoryInputItemView1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiffNo", DbType="BigInt")]
		public System.Nullable<long> DiffNo
		{
			get
			{
				return this._DiffNo;
			}
			set
			{
				if ((this._DiffNo != value))
				{
					this._DiffNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeEx", DbType="NVarChar(50)")]
		public string CodeEx
		{
			get
			{
				return this._CodeEx;
			}
			set
			{
				if ((this._CodeEx != value))
				{
					this._CodeEx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="Binary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this._Barcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expiry", DbType="Bit")]
		public System.Nullable<bool> Expiry
		{
			get
			{
				return this._Expiry;
			}
			set
			{
				if ((this._Expiry != value))
				{
					this._Expiry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryEx", DbType="NVarChar(250)")]
		public string ExpiryEx
		{
			get
			{
				return this._ExpiryEx;
			}
			set
			{
				if ((this._ExpiryEx != value))
				{
					this._ExpiryEx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LottNo", DbType="NVarChar(50)")]
		public string LottNo
		{
			get
			{
				return this._LottNo;
			}
			set
			{
				if ((this._LottNo != value))
				{
					this._LottNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Real")]
		public System.Nullable<float> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceIn", DbType="BigInt")]
		public System.Nullable<long> PriceIn
		{
			get
			{
				return this._PriceIn;
			}
			set
			{
				if ((this._PriceIn != value))
				{
					this._PriceIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductPurchase", DbType="BigInt")]
		public System.Nullable<long> IdProductPurchase
		{
			get
			{
				return this._IdProductPurchase;
			}
			set
			{
				if ((this._IdProductPurchase != value))
				{
					this._IdProductPurchase = value;
				}
			}
		}

        public int RowNumber { get; set; }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InventoryView1")]
	public partial class InventoryView1
	{
		
		private long _Id;
		
		private string _Code;
		
		private string _Name;
		
		private System.Nullable<long> _DiffNo;
		
		private string _CodeEx;
		
		private System.Nullable<long> _Expiry;
		
		private string _ExpiryEx;
		
		private string _LottNo;
		
		private System.Nullable<long> _CreatedDate;
		
		private string _CreatedDateEx;
		
		private System.Nullable<long> _PriceIn;
		
		private System.Nullable<decimal> _PriceOut;
		
		private System.Nullable<long> _IdInvoice;
		
		private System.Nullable<long> _IdInvoiceOut;
		
		private System.Nullable<int> _IdInventoryStorage;
		
		private System.Nullable<bool> _IsOutput;
		
		private System.Nullable<bool> _IsGiven;
		
		private System.Nullable<int> _StockLimit;
		
		private System.Nullable<int> _ExpiryLimit;
		
		private System.Nullable<int> _IdProductKind;
		
		private string _KindName;
		
		private string _ManufactureName;
		
		private string _StorageName;
		
		public InventoryView1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(250)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiffNo", DbType="BigInt")]
		public System.Nullable<long> DiffNo
		{
			get
			{
				return this._DiffNo;
			}
			set
			{
				if ((this._DiffNo != value))
				{
					this._DiffNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeEx", DbType="NVarChar(250)")]
		public string CodeEx
		{
			get
			{
				return this._CodeEx;
			}
			set
			{
				if ((this._CodeEx != value))
				{
					this._CodeEx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expiry", DbType="BigInt")]
		public System.Nullable<long> Expiry
		{
			get
			{
				return this._Expiry;
			}
			set
			{
				if ((this._Expiry != value))
				{
					this._Expiry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryEx", DbType="NVarChar(250)")]
		public string ExpiryEx
		{
			get
			{
				return this._ExpiryEx;
			}
			set
			{
				if ((this._ExpiryEx != value))
				{
					this._ExpiryEx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LottNo", DbType="NVarChar(50)")]
		public string LottNo
		{
			get
			{
				return this._LottNo;
			}
			set
			{
				if ((this._LottNo != value))
				{
					this._LottNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="BigInt")]
		public System.Nullable<long> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDateEx", DbType="NVarChar(250)")]
		public string CreatedDateEx
		{
			get
			{
				return this._CreatedDateEx;
			}
			set
			{
				if ((this._CreatedDateEx != value))
				{
					this._CreatedDateEx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceIn", DbType="BigInt")]
		public System.Nullable<long> PriceIn
		{
			get
			{
				return this._PriceIn;
			}
			set
			{
				if ((this._PriceIn != value))
				{
					this._PriceIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceOut", DbType="Money")]
		public System.Nullable<decimal> PriceOut
		{
			get
			{
				return this._PriceOut;
			}
			set
			{
				if ((this._PriceOut != value))
				{
					this._PriceOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInvoice", DbType="BigInt")]
		public System.Nullable<long> IdInvoice
		{
			get
			{
				return this._IdInvoice;
			}
			set
			{
				if ((this._IdInvoice != value))
				{
					this._IdInvoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInvoiceOut", DbType="BigInt")]
		public System.Nullable<long> IdInvoiceOut
		{
			get
			{
				return this._IdInvoiceOut;
			}
			set
			{
				if ((this._IdInvoiceOut != value))
				{
					this._IdInvoiceOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInventoryStorage", DbType="Int")]
		public System.Nullable<int> IdInventoryStorage
		{
			get
			{
				return this._IdInventoryStorage;
			}
			set
			{
				if ((this._IdInventoryStorage != value))
				{
					this._IdInventoryStorage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOutput", DbType="Bit")]
		public System.Nullable<bool> IsOutput
		{
			get
			{
				return this._IsOutput;
			}
			set
			{
				if ((this._IsOutput != value))
				{
					this._IsOutput = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsGiven", DbType="Bit")]
		public System.Nullable<bool> IsGiven
		{
			get
			{
				return this._IsGiven;
			}
			set
			{
				if ((this._IsGiven != value))
				{
					this._IsGiven = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockLimit", DbType="Int")]
		public System.Nullable<int> StockLimit
		{
			get
			{
				return this._StockLimit;
			}
			set
			{
				if ((this._StockLimit != value))
				{
					this._StockLimit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryLimit", DbType="Int")]
		public System.Nullable<int> ExpiryLimit
		{
			get
			{
				return this._ExpiryLimit;
			}
			set
			{
				if ((this._ExpiryLimit != value))
				{
					this._ExpiryLimit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductKind", DbType="Int")]
		public System.Nullable<int> IdProductKind
		{
			get
			{
				return this._IdProductKind;
			}
			set
			{
				if ((this._IdProductKind != value))
				{
					this._IdProductKind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KindName", DbType="NVarChar(50)")]
		public string KindName
		{
			get
			{
				return this._KindName;
			}
			set
			{
				if ((this._KindName != value))
				{
					this._KindName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManufactureName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ManufactureName
		{
			get
			{
				return this._ManufactureName;
			}
			set
			{
				if ((this._ManufactureName != value))
				{
					this._ManufactureName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StorageName", DbType="NVarChar(50)")]
		public string StorageName
		{
			get
			{
				return this._StorageName;
			}
			set
			{
				if ((this._StorageName != value))
				{
					this._StorageName = value;
				}
			}
		}

        public int RowNumber { get; set; }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InventoryInputItemGroupView")]
	public partial class InventoryInputItemGroupView
	{
		
		private string _Code;
		
		private string _Name;
		
		private System.Nullable<double> _Quantity;
		
		private System.Nullable<long> _PriceIn;
		
		private System.Nullable<long> _IdProductPurchase;
		
		private string _UnitName;
		
		public InventoryInputItemGroupView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float")]
		public System.Nullable<double> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceIn", DbType="BigInt")]
		public System.Nullable<long> PriceIn
		{
			get
			{
				return this._PriceIn;
			}
			set
			{
				if ((this._PriceIn != value))
				{
					this._PriceIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductPurchase", DbType="BigInt")]
		public System.Nullable<long> IdProductPurchase
		{
			get
			{
				return this._IdProductPurchase;
			}
			set
			{
				if ((this._IdProductPurchase != value))
				{
					this._IdProductPurchase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UnitName
		{
			get
			{
				return this._UnitName;
			}
			set
			{
				if ((this._UnitName != value))
				{
					this._UnitName = value;
				}
			}
		}

        public int RowNumber { get; set; }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductCustomerCreditLimitView")]
	public partial class ProductCustomerCreditLimitView
	{
		
		private int _Id;
		
		private string _Code;
		
		private string _Name;
		
		private string _ManufactureName;
		
		private string _ProductKindName;
		
		private System.Nullable<int> _Quantity;
		
		private System.Nullable<long> _IdCustomer;
		
		public ProductCustomerCreditLimitView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManufactureName", DbType="NVarChar(50)")]
		public string ManufactureName
		{
			get
			{
				return this._ManufactureName;
			}
			set
			{
				if ((this._ManufactureName != value))
				{
					this._ManufactureName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductKindName", DbType="NVarChar(50)")]
		public string ProductKindName
		{
			get
			{
				return this._ProductKindName;
			}
			set
			{
				if ((this._ProductKindName != value))
				{
					this._ProductKindName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
		public System.Nullable<int> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCustomer", DbType="BigInt")]
		public System.Nullable<long> IdCustomer
		{
			get
			{
				return this._IdCustomer;
			}
			set
			{
				if ((this._IdCustomer != value))
				{
					this._IdCustomer = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductView")]
	public partial class ProductView1
	{
		
		private int _Id;
		
		private string _Code;
		
		private string _Name;
		
		private System.Nullable<decimal> _PriceIn;
		
		private System.Nullable<decimal> _PriceOut;
		
		private string _UnitName;
		
		private string _GroupName;
		
		private string _ManufactureName;
		
		private System.Nullable<int> _IdProductKind;
		
		private string _ProductKindName;
		
		private string _ProductColorName;
		
		private string _RefNo;
		
		private string _ExpiryRule;
		
		private string _LottNoRule;
		
		private System.Nullable<int> _StockLimit;
		
		private System.Nullable<int> _ExpiryLimit;
		
		private System.Nullable<int> _RefNoLenth;
		
		private System.Nullable<bool> _IsBOM;
		
		public ProductView1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceIn", DbType="Money")]
		public System.Nullable<decimal> PriceIn
		{
			get
			{
				return this._PriceIn;
			}
			set
			{
				if ((this._PriceIn != value))
				{
					this._PriceIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceOut", DbType="Money")]
		public System.Nullable<decimal> PriceOut
		{
			get
			{
				return this._PriceOut;
			}
			set
			{
				if ((this._PriceOut != value))
				{
					this._PriceOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitName", DbType="NVarChar(50)")]
		public string UnitName
		{
			get
			{
				return this._UnitName;
			}
			set
			{
				if ((this._UnitName != value))
				{
					this._UnitName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(50)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this._GroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManufactureName", DbType="NVarChar(50)")]
		public string ManufactureName
		{
			get
			{
				return this._ManufactureName;
			}
			set
			{
				if ((this._ManufactureName != value))
				{
					this._ManufactureName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductKind", DbType="Int")]
		public System.Nullable<int> IdProductKind
		{
			get
			{
				return this._IdProductKind;
			}
			set
			{
				if ((this._IdProductKind != value))
				{
					this._IdProductKind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductKindName", DbType="NVarChar(50)")]
		public string ProductKindName
		{
			get
			{
				return this._ProductKindName;
			}
			set
			{
				if ((this._ProductKindName != value))
				{
					this._ProductKindName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductColorName", DbType="NVarChar(54)")]
		public string ProductColorName
		{
			get
			{
				return this._ProductColorName;
			}
			set
			{
				if ((this._ProductColorName != value))
				{
					this._ProductColorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefNo", DbType="NVarChar(50)")]
		public string RefNo
		{
			get
			{
				return this._RefNo;
			}
			set
			{
				if ((this._RefNo != value))
				{
					this._RefNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryRule", DbType="NVarChar(50)")]
		public string ExpiryRule
		{
			get
			{
				return this._ExpiryRule;
			}
			set
			{
				if ((this._ExpiryRule != value))
				{
					this._ExpiryRule = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LottNoRule", DbType="NVarChar(50)")]
		public string LottNoRule
		{
			get
			{
				return this._LottNoRule;
			}
			set
			{
				if ((this._LottNoRule != value))
				{
					this._LottNoRule = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockLimit", DbType="Int")]
		public System.Nullable<int> StockLimit
		{
			get
			{
				return this._StockLimit;
			}
			set
			{
				if ((this._StockLimit != value))
				{
					this._StockLimit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryLimit", DbType="Int")]
		public System.Nullable<int> ExpiryLimit
		{
			get
			{
				return this._ExpiryLimit;
			}
			set
			{
				if ((this._ExpiryLimit != value))
				{
					this._ExpiryLimit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefNoLenth", DbType="Int")]
		public System.Nullable<int> RefNoLenth
		{
			get
			{
				return this._RefNoLenth;
			}
			set
			{
				if ((this._RefNoLenth != value))
				{
					this._RefNoLenth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBOM", DbType="Bit")]
		public System.Nullable<bool> IsBOM
		{
			get
			{
				return this._IsBOM;
			}
			set
			{
				if ((this._IsBOM != value))
				{
					this._IsBOM = value;
				}
			}
		}

        public int RowNumber { get; set; }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Code;
		
		private string _Name;
		
		private string _RefNo;
		
		private System.Nullable<int> _RefNoLenth;
		
		private System.Nullable<decimal> _PriceIn;
		
		private System.Nullable<decimal> _PriceOut;
		
		private System.Nullable<int> _IdUnit;
		
		private System.Nullable<int> _IdProductColor;
		
		private System.Nullable<int> _IdProductKind;
		
		private System.Nullable<int> _IdGroup;
		
		private System.Nullable<int> _IdManufacture;
		
		private string _InventoryType;
		
		private string _ExpiryRule;
		
		private string _LottNoRule;
		
		private System.Nullable<int> _StockLimit;
		
		private System.Nullable<int> _ExpiryLimit;
		
		private System.Nullable<bool> _IsBOM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnRefNoChanging(string value);
    partial void OnRefNoChanged();
    partial void OnRefNoLenthChanging(System.Nullable<int> value);
    partial void OnRefNoLenthChanged();
    partial void OnPriceInChanging(System.Nullable<decimal> value);
    partial void OnPriceInChanged();
    partial void OnPriceOutChanging(System.Nullable<decimal> value);
    partial void OnPriceOutChanged();
    partial void OnIdUnitChanging(System.Nullable<int> value);
    partial void OnIdUnitChanged();
    partial void OnIdProductColorChanging(System.Nullable<int> value);
    partial void OnIdProductColorChanged();
    partial void OnIdProductKindChanging(System.Nullable<int> value);
    partial void OnIdProductKindChanged();
    partial void OnIdGroupChanging(System.Nullable<int> value);
    partial void OnIdGroupChanged();
    partial void OnIdManufactureChanging(System.Nullable<int> value);
    partial void OnIdManufactureChanged();
    partial void OnInventoryTypeChanging(string value);
    partial void OnInventoryTypeChanged();
    partial void OnExpiryRuleChanging(string value);
    partial void OnExpiryRuleChanged();
    partial void OnLottNoRuleChanging(string value);
    partial void OnLottNoRuleChanged();
    partial void OnStockLimitChanging(System.Nullable<int> value);
    partial void OnStockLimitChanged();
    partial void OnExpiryLimitChanging(System.Nullable<int> value);
    partial void OnExpiryLimitChanged();
    partial void OnIsBOMChanging(System.Nullable<bool> value);
    partial void OnIsBOMChanged();
    #endregion
		
		public Product1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefNo", DbType="NVarChar(50)")]
		public string RefNo
		{
			get
			{
				return this._RefNo;
			}
			set
			{
				if ((this._RefNo != value))
				{
					this.OnRefNoChanging(value);
					this.SendPropertyChanging();
					this._RefNo = value;
					this.SendPropertyChanged("RefNo");
					this.OnRefNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefNoLenth", DbType="Int")]
		public System.Nullable<int> RefNoLenth
		{
			get
			{
				return this._RefNoLenth;
			}
			set
			{
				if ((this._RefNoLenth != value))
				{
					this.OnRefNoLenthChanging(value);
					this.SendPropertyChanging();
					this._RefNoLenth = value;
					this.SendPropertyChanged("RefNoLenth");
					this.OnRefNoLenthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceIn", DbType="Money")]
		public System.Nullable<decimal> PriceIn
		{
			get
			{
				return this._PriceIn;
			}
			set
			{
				if ((this._PriceIn != value))
				{
					this.OnPriceInChanging(value);
					this.SendPropertyChanging();
					this._PriceIn = value;
					this.SendPropertyChanged("PriceIn");
					this.OnPriceInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceOut", DbType="Money")]
		public System.Nullable<decimal> PriceOut
		{
			get
			{
				return this._PriceOut;
			}
			set
			{
				if ((this._PriceOut != value))
				{
					this.OnPriceOutChanging(value);
					this.SendPropertyChanging();
					this._PriceOut = value;
					this.SendPropertyChanged("PriceOut");
					this.OnPriceOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUnit", DbType="Int")]
		public System.Nullable<int> IdUnit
		{
			get
			{
				return this._IdUnit;
			}
			set
			{
				if ((this._IdUnit != value))
				{
					this.OnIdUnitChanging(value);
					this.SendPropertyChanging();
					this._IdUnit = value;
					this.SendPropertyChanged("IdUnit");
					this.OnIdUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductColor", DbType="Int")]
		public System.Nullable<int> IdProductColor
		{
			get
			{
				return this._IdProductColor;
			}
			set
			{
				if ((this._IdProductColor != value))
				{
					this.OnIdProductColorChanging(value);
					this.SendPropertyChanging();
					this._IdProductColor = value;
					this.SendPropertyChanged("IdProductColor");
					this.OnIdProductColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductKind", DbType="Int")]
		public System.Nullable<int> IdProductKind
		{
			get
			{
				return this._IdProductKind;
			}
			set
			{
				if ((this._IdProductKind != value))
				{
					this.OnIdProductKindChanging(value);
					this.SendPropertyChanging();
					this._IdProductKind = value;
					this.SendPropertyChanged("IdProductKind");
					this.OnIdProductKindChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGroup", DbType="Int")]
		public System.Nullable<int> IdGroup
		{
			get
			{
				return this._IdGroup;
			}
			set
			{
				if ((this._IdGroup != value))
				{
					this.OnIdGroupChanging(value);
					this.SendPropertyChanging();
					this._IdGroup = value;
					this.SendPropertyChanged("IdGroup");
					this.OnIdGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdManufacture", DbType="Int")]
		public System.Nullable<int> IdManufacture
		{
			get
			{
				return this._IdManufacture;
			}
			set
			{
				if ((this._IdManufacture != value))
				{
					this.OnIdManufactureChanging(value);
					this.SendPropertyChanging();
					this._IdManufacture = value;
					this.SendPropertyChanged("IdManufacture");
					this.OnIdManufactureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InventoryType", DbType="NVarChar(50)")]
		public string InventoryType
		{
			get
			{
				return this._InventoryType;
			}
			set
			{
				if ((this._InventoryType != value))
				{
					this.OnInventoryTypeChanging(value);
					this.SendPropertyChanging();
					this._InventoryType = value;
					this.SendPropertyChanged("InventoryType");
					this.OnInventoryTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryRule", DbType="NVarChar(50)")]
		public string ExpiryRule
		{
			get
			{
				return this._ExpiryRule;
			}
			set
			{
				if ((this._ExpiryRule != value))
				{
					this.OnExpiryRuleChanging(value);
					this.SendPropertyChanging();
					this._ExpiryRule = value;
					this.SendPropertyChanged("ExpiryRule");
					this.OnExpiryRuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LottNoRule", DbType="NVarChar(50)")]
		public string LottNoRule
		{
			get
			{
				return this._LottNoRule;
			}
			set
			{
				if ((this._LottNoRule != value))
				{
					this.OnLottNoRuleChanging(value);
					this.SendPropertyChanging();
					this._LottNoRule = value;
					this.SendPropertyChanged("LottNoRule");
					this.OnLottNoRuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockLimit", DbType="Int")]
		public System.Nullable<int> StockLimit
		{
			get
			{
				return this._StockLimit;
			}
			set
			{
				if ((this._StockLimit != value))
				{
					this.OnStockLimitChanging(value);
					this.SendPropertyChanging();
					this._StockLimit = value;
					this.SendPropertyChanged("StockLimit");
					this.OnStockLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiryLimit", DbType="Int")]
		public System.Nullable<int> ExpiryLimit
		{
			get
			{
				return this._ExpiryLimit;
			}
			set
			{
				if ((this._ExpiryLimit != value))
				{
					this.OnExpiryLimitChanging(value);
					this.SendPropertyChanging();
					this._ExpiryLimit = value;
					this.SendPropertyChanged("ExpiryLimit");
					this.OnExpiryLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBOM", DbType="Bit")]
		public System.Nullable<bool> IsBOM
		{
			get
			{
				return this._IsBOM;
			}
			set
			{
				if ((this._IsBOM != value))
				{
					this.OnIsBOMChanging(value);
					this.SendPropertyChanging();
					this._IsBOM = value;
					this.SendPropertyChanged("IsBOM");
					this.OnIsBOMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductPurchaseView")]
	public partial class ProductPurchaseView1
	{
		
		private long _Id;
		
		private string _InvoiceNo;
		
		private System.Nullable<long> _CreatedDate;
		
		private string _CreatedDateEx;
		
		private System.Nullable<long> _InvoiceDate;
		
		private string _InvoiceDateEx;
		
		private string _VendorName;
		
		private System.Nullable<long> _Amount;
		
		private System.Nullable<long> _Discount;
		
		private System.Nullable<long> _Payment;
		
		private System.Nullable<bool> _IsDone;
		
		private string _Kind;
		
		private string _CustomerName;
		
		public ProductPurchaseView1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo", DbType="NVarChar(50)")]
		public string InvoiceNo
		{
			get
			{
				return this._InvoiceNo;
			}
			set
			{
				if ((this._InvoiceNo != value))
				{
					this._InvoiceNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="BigInt")]
		public System.Nullable<long> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDateEx", DbType="NVarChar(50)")]
		public string CreatedDateEx
		{
			get
			{
				return this._CreatedDateEx;
			}
			set
			{
				if ((this._CreatedDateEx != value))
				{
					this._CreatedDateEx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="BigInt")]
		public System.Nullable<long> InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this._InvoiceDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDateEx", DbType="NVarChar(50)")]
		public string InvoiceDateEx
		{
			get
			{
				return this._InvoiceDateEx;
			}
			set
			{
				if ((this._InvoiceDateEx != value))
				{
					this._InvoiceDateEx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="NVarChar(50)")]
		public string VendorName
		{
			get
			{
				return this._VendorName;
			}
			set
			{
				if ((this._VendorName != value))
				{
					this._VendorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="BigInt")]
		public System.Nullable<long> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="BigInt")]
		public System.Nullable<long> Discount
		{
			get
			{
				return this._Discount;
			}
			set
			{
				if ((this._Discount != value))
				{
					this._Discount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment", DbType="BigInt")]
		public System.Nullable<long> Payment
		{
			get
			{
				return this._Payment;
			}
			set
			{
				if ((this._Payment != value))
				{
					this._Payment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDone", DbType="Bit")]
		public System.Nullable<bool> IsDone
		{
			get
			{
				return this._IsDone;
			}
			set
			{
				if ((this._IsDone != value))
				{
					this._IsDone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kind", DbType="NVarChar(50)")]
		public string Kind
		{
			get
			{
				return this._Kind;
			}
			set
			{
				if ((this._Kind != value))
				{
					this._Kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(50)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}

        public int RowNumber { get; set; }

        public bool VendorVisibility { get; set; }

        public bool CustomerVisibility { get; set; }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerCreditLimitView")]
	public partial class CustomerCreditLimitView
	{
		
		private long _Id;
		
		private long _IdCustomer;
		
		private int _IdProductKind;
		
		private string _Kind;
		
		private int _Quantity;
		
		public CustomerCreditLimitView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCustomer", DbType="BigInt NOT NULL")]
		public long IdCustomer
		{
			get
			{
				return this._IdCustomer;
			}
			set
			{
				if ((this._IdCustomer != value))
				{
					this._IdCustomer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProductKind", DbType="Int NOT NULL")]
		public int IdProductKind
		{
			get
			{
				return this._IdProductKind;
			}
			set
			{
				if ((this._IdProductKind != value))
				{
					this._IdProductKind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kind", DbType="NVarChar(50)")]
		public string Kind
		{
			get
			{
				return this._Kind;
			}
			set
			{
				if ((this._Kind != value))
				{
					this._Kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}

        public int RowNumber { get; set; }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductSaleView")]
	public partial class ProductSaleView1
	{
		
		private long _Id;
		
		private string _InvoiceNo;
		
		private System.Nullable<long> _CreatedDate;
		
		private string _CreatedDateEx;
		
		private string _InvoiceDateEx;
		
		private System.Nullable<long> _IdStaff;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<decimal> _Discount;
		
		private System.Nullable<decimal> _Payment;
		
		private System.Nullable<bool> _IsDone;
		
		private string _Address;
		
		private string _CustomerName;
		
		private System.Nullable<long> _InvoiceDate;
		
		private System.Nullable<long> _IdStaffSale;
		
		private System.Nullable<bool> _IsGiven;
		
		private string _Kind;
		
		private string _StaffName;
		
		private string _Notes;
		
		private string _VendorName;
		
		public ProductSaleView1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo", DbType="NVarChar(50)")]
		public string InvoiceNo
		{
			get
			{
				return this._InvoiceNo;
			}
			set
			{
				if ((this._InvoiceNo != value))
				{
					this._InvoiceNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="BigInt")]
		public System.Nullable<long> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDateEx", DbType="NVarChar(50)")]
		public string CreatedDateEx
		{
			get
			{
				return this._CreatedDateEx;
			}
			set
			{
				if ((this._CreatedDateEx != value))
				{
					this._CreatedDateEx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDateEx", DbType="NVarChar(50)")]
		public string InvoiceDateEx
		{
			get
			{
				return this._InvoiceDateEx;
			}
			set
			{
				if ((this._InvoiceDateEx != value))
				{
					this._InvoiceDateEx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStaff", DbType="BigInt")]
		public System.Nullable<long> IdStaff
		{
			get
			{
				return this._IdStaff;
			}
			set
			{
				if ((this._IdStaff != value))
				{
					this._IdStaff = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="Money")]
		public System.Nullable<decimal> Discount
		{
			get
			{
				return this._Discount;
			}
			set
			{
				if ((this._Discount != value))
				{
					this._Discount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment", DbType="Money")]
		public System.Nullable<decimal> Payment
		{
			get
			{
				return this._Payment;
			}
			set
			{
				if ((this._Payment != value))
				{
					this._Payment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDone", DbType="Bit")]
		public System.Nullable<bool> IsDone
		{
			get
			{
				return this._IsDone;
			}
			set
			{
				if ((this._IsDone != value))
				{
					this._IsDone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(250)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(50)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="BigInt")]
		public System.Nullable<long> InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this._InvoiceDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStaffSale", DbType="BigInt")]
		public System.Nullable<long> IdStaffSale
		{
			get
			{
				return this._IdStaffSale;
			}
			set
			{
				if ((this._IdStaffSale != value))
				{
					this._IdStaffSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsGiven", DbType="Bit")]
		public System.Nullable<bool> IsGiven
		{
			get
			{
				return this._IsGiven;
			}
			set
			{
				if ((this._IsGiven != value))
				{
					this._IsGiven = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kind", DbType="NVarChar(250)")]
		public string Kind
		{
			get
			{
				return this._Kind;
			}
			set
			{
				if ((this._Kind != value))
				{
					this._Kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string StaffName
		{
			get
			{
				return this._StaffName;
			}
			set
			{
				if ((this._StaffName != value))
				{
					this._StaffName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="NVarChar(200)")]
		public string VendorName
		{
			get
			{
				return this._VendorName;
			}
			set
			{
				if ((this._VendorName != value))
				{
					this._VendorName = value;
				}
			}
		}

        public int RowNumber { get; set; }
    }
}
#pragma warning restore 1591
