//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-CEFGNA7\\SQLEXPRESS;Initial Catalog=SmallERP_HuongTrinh;User I" +
            "D=sa;Password=tv123456789;Encrypt=False;TrustServerCertificate=True")]
        public string SmallERPConnectionString {
            get {
                return ((string)(this["SmallERPConnectionString"]));
            }
            set
            {
                this["SmallERPConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StaffName {
            get {
                return ((string)(this["StaffName"]));
            }
            set {
                this["StaffName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserGroupName {
            get {
                return ((string)(this["UserGroupName"]));
            }
            set {
                this["UserGroupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IdStaff {
            get {
                return ((int)(this["IdStaff"]));
            }
            set {
                this["IdStaff"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HL1O11A\\SQLEXPRESS;Initial Catalog=SmallERP;User ID=sa")]
        public string SmallERPConnectionString1 {
            get {
                return ((string)(this["SmallERPConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HL1O11A\\SQLEXPRESS;Initial Catalog=SmallERP;User ID=sa;Passwo" +
            "rd=tv123456789")]
        public string SmallERPConnectionString2 {
            get {
                return ((string)(this["SmallERPConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HL1O11A\\SQLEXPRESS;Initial Catalog=SmallERP_AnHuy;User ID=sa;" +
            "Password=tv123456789")]
        public string SmallERP_AnHuyConnectionString {
            get {
                return ((string)(this["SmallERP_AnHuyConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HL1O11A\\SQLEXPRESS;Initial Catalog=SmallERP_SDIVINA;User ID=s" +
            "a;Password=tv123456789")]
        public string SmallERP_SDIVINAConnectionString {
            get {
                return ((string)(this["SmallERP_SDIVINAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=vuhuy.database.windows.net;Initial Catalog=SmallERP_SDIVINA;User ID=a" +
            "bcxyz;Password=tv123456789@179")]
        public string SmallERP_SDIVINAConnectionString1 {
            get {
                return ((string)(this["SmallERP_SDIVINAConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-CEFGNA7\\SQLEXPRESS;Initial Catalog=SmallERP_SDIVINA;User ID=s" +
            "a;Password=xd123456789")]
        public string SmallERP_SDIVINAConnectionString2 {
            get {
                return ((string)(this["SmallERP_SDIVINAConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-CEFGNA7\\SQLEXPRESS;Initial Catalog=SmallERP_SDIVINA;Persist S" +
            "ecurity Info=True;User ID=sa;Password=tv123456789")]
        public string SmallERP_SDIVINAConnectionString3 {
            get {
                return ((string)(this["SmallERP_SDIVINAConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-CEFGNA7\\SQLEXPRESS;Initial Catalog=SmallERP_HuongTrinh;User I" +
            "D=sa;Password=tv123456789")]
        public string SmallERP_HuongTrinhConnectionString {
            get {
                return ((string)(this["SmallERP_HuongTrinhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-CEFGNA7\\SQLEXPRESS;Initial Catalog=SmallERP_AnHuy;User ID=sa;" +
            "Password=tv123456789;Encrypt=False;TrustServerCertificate=True")]
        public string SmallERP_AnHuyConnectionString1 {
            get {
                return ((string)(this["SmallERP_AnHuyConnectionString1"]));
            }
        }
    }
}
